//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_v._1._0.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int employeeID { get; set; }
        public string eUserName { get; set; }
        public string eUserPassword { get; set; }
        public string eFirstName { get; set; }
        public string eLastName { get; set; }
        public string email { get; set; }
        public Nullable<int> officeCode { get; set; }
        public string jobTitle { get; set; }
        public Nullable<int> signinID { get; set; }
    
        public virtual Signin Signin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
