//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_v._1._0.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int regionID { get; set; }
        public string regionName { get; set; }
        public string postalCode { get; set; }
        public Nullable<int> cityID { get; set; }
    
        public virtual City City { get; set; }
    }
}
